#Display Attributes
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
BACKGROUND_COLOR = (0,0,0)

#Asteroid Attributes
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_COLOR = (200,0,0)
ASTEROID_LINE_WIDTH = 2

#Player Attributes
PLAYER_RADIUS = 20
PLAYER_COLOR = (0,255,0)
PLAYER_LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_MOVE_SPEED = 200